# Generated by Django 5.1.3 on 2025-11-13 22:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_url', models.URLField(verbose_name='URL do Produto')),
                ('product_name', models.CharField(max_length=500, verbose_name='Nome do Produto')),
                ('product_image_url', models.URLField(verbose_name='URL da Imagem Original')),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('commission_rate', models.CharField(blank=True, max_length=20, null=True)),
                ('shop_name', models.CharField(blank=True, max_length=200, null=True)),
                ('rating', models.CharField(blank=True, max_length=10, null=True)),
                ('promo_text', models.TextField(max_length=500, verbose_name='Texto Promocional')),
                ('promo_image', models.ImageField(upload_to='promos/', verbose_name='Imagem Gerada')),
                ('affiliate_link', models.URLField(blank=True, verbose_name='Link de Afiliado')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('views', models.IntegerField(default=0, verbose_name='Visualizações')),
            ],
            options={
                'verbose_name': 'Promoção de Produto',
                'verbose_name_plural': 'Promoções de Produtos',
                'ordering': ['-created_at'],
            },
        ),
    ]
